### ISSUE TITLE
Request project data from API once per run and memoize

### ISSUE THREAD

**Issue by camallen** [RonaCostello/twitter-bot#2]
Re https://github.com/RonaCostello/twitter-bot/blob/11b55f5125fe337bec40fb8c7308f6a76a5be15b/tweetbot/randomproject.py#L8

Can we extract this to a memoized function (https://en.wikipedia.org/wiki/Memoization) to avoid running API requests each time i request a random project. 

Feel free to close if this functions is only ever called once per execution run. Although it would be an ideal optimization anyway.

**Comment by RonaCostello** [comment]
Yeah it can, and it is the currently the biggest bottleneck time wise. Good shout 👍
